// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADMnJdDdTE8Le-pa-APtPYpnOpxW4HQPU',
    appId: '1:177096419584:web:a899f03cedd6d2c3e6ebe5',
    messagingSenderId: '177096419584',
    projectId: 'rad-onc-in-service',
    authDomain: 'rad-onc-in-service.firebaseapp.com',
    storageBucket: 'rad-onc-in-service.appspot.com',
    measurementId: 'G-LR8QDPPPDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0zMO84gTDldGGOaGYS5uRPhOb5wh7G90',
    appId: '1:177096419584:android:375fdea95951b020e6ebe5',
    messagingSenderId: '177096419584',
    projectId: 'rad-onc-in-service',
    storageBucket: 'rad-onc-in-service.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNO9MZJMX0Nk01VXK_XOBmxeNGDySwTHw',
    appId: '1:177096419584:ios:6d1bd4c3ad756d10e6ebe5',
    messagingSenderId: '177096419584',
    projectId: 'rad-onc-in-service',
    storageBucket: 'rad-onc-in-service.appspot.com',
    iosClientId: '177096419584-nnqentlfonv41kl18hr0nd2t0bqfekmq.apps.googleusercontent.com',
    iosBundleId: 'com.radoncinservice.app',
  );
}
